"""Addded origin_url to Repost model

Revision ID: 15f71d675cee
Revises: fcb9759b4068
Create Date: 2024-11-17 14:48:24.760041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15f71d675cee'
down_revision: Union[str, None] = 'fcb9759b4068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reposts', sa.Column('origin_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reposts', 'origin_url')
    # ### end Alembic commands ###
