"""add url atr to Note

Revision ID: 850971cc5b2d
Revises: 27e4ee7d248a
Create Date: 2024-10-26 14:59:00.063683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850971cc5b2d'
down_revision: Union[str, None] = '27e4ee7d248a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'url')
    # ### end Alembic commands ###
