"""Added reposts relationship to User model

Revision ID: fcb9759b4068
Revises: c81e8d1b45ba
Create Date: 2024-10-27 18:30:26.133543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb9759b4068'
down_revision: Union[str, None] = 'c81e8d1b45ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
